### ISSUE TITLE
How add Legend patch shapes in QGIS 3.12.2 ? 

### ISSUE THREAD

**Issue by ambarja** [kartoza/QGIS-Legend-Patches#8]
First I want  congratulation you for this excellent work and contribute to QGIS community, it's amazing!.
At moment I'm using  **QGIS 3.12.2** and I don't see Legend patch shapes.
Thanks!
![](https://github.com/barja8/Friends/blob/master/QGIS/Img/Question_about_qgis.png?raw=true)

**Comment by pigreco** [comment]
@barja8 

It is a feature present in the master, it will be available from 3.14 onwards (June 2020)

**Comment by ambarja** [comment]
@pigreco  thanks very much for the information :nerd_face:
